apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: productreview-deploy
  namespace: shoppingportal
spec:
  replicas: 1
  selector:
    matchLabels:
      name: productreview
      zone: prod
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        name: productreview
        version: "1.0.0"
        release: stable
        tier: fe
        zone: prod
        managed-by: m2
    spec:
      containers:
        - name: productreview-ctr
          image: metamagicglobal/productreviewms
          imagePullPolicy: Always
          ports:
          - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /productreviewms/check/live
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 15          
